name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "master" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: mlotta183
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Write RSA key
      uses: DamianReeves/write-file-action@master
      with:
        path: encryptionkeys/jwt.key
        contents: |
          ${{ secrets.RSA_PRIVATE_KEY }}
        write-mode: append

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context: 
       push: true
       tags: mlotta183/juice-shop-hmp:latest